### ISSUE TITLE
Can't enable Nautilus integration (flatpak install)

### ISSUE THREAD

**Issue by alduraibi** [syncthing-gtk/syncthing-gtk#34]
Is there a way to use the Nautilus integration if I have the flatpak version of Syncthing GTK installed? The option is currently greyed out for me.

**Comment by Salamandar** [comment]
Hello, I'm not sure. Syncthing-gtk needs to detect the presence of Nautilus and to be able to copy files into the Nautilus configuration directory…

**Comment by stingray21** [comment]
I have the same issue, with the AUR version. The `python-nautilus` is installed

**Comment by Salamandar** [comment]
@stingray21 Can you try with syncthing-gtk-git ? I think this was fixed since the last release.

**Comment by stingray21** [comment]
@Salamandar Thanks for the reply, I installed syncthing-gtk-git via pamac and restarted syncthing-gtk, but unfortunately still the same.
